language: go
go:
    - 1.8.x
    - 1.9.x
    - 1.10.x

install:
    - go get -u golang.org/x/tools/cmd/goimports
    - go get -u github.com/mattn/goveralls
    - go get -u github.com/alecthomas/gometalinter
    - gometalinter --install --vendor
    - curl https://glide.sh/get | sh

script:
  - make local cover
